#!/bin/bash
#
# 80 percent solution for jobwatch
#

DATE=$(date +"%Y-%m-%d")

git pull


# TODO: create a DSL to represent job pages
wget -O puppet 'https://boards.greenhouse.io/embed/job_board?for=puppetinc&b=https://puppet.com/company/careers/jobs'
wget -O newrelic 'https://newrelic.com/about/careers'
wget -O pagerduty 'https://www.pagerduty.com/wp-content/themes/startit-child/assets/js/json/jobs/'
wget -O sentry 'https://sentry.io/jobs/'

#normalize html
sed -i -e 's/\<script.*script\>//' -e 's/\<meta .*\>//' puppet
sed -i -e 's/\<script.*script\>//' -e 's/\<meta .*\>//' newrelic
sed -i -e 's/<link rel="stylesheet".*\">//' sentry

#normalize json
cat pagerduty | jq . | sponge pagerduty

# send to github
git add .
git commit -m "new jobs found on $DATE"
git push
